UglyTAGS = [',' , "''" , '#' , '$' , '.' , ':' ,'``']
TAGS = ['PRP$', 'VBG', 'VBD', 'VBN', 'VBP', 'WDT', 'JJ', 'WP', 'VBZ', 'DT', 'RP', 'NN', 'FW', 'POS', 'TO', 'LS','RB', 'NNS', 'PRP', 'VB', 'WRB', 'CC', 'PDT', 'RBS', 'RBR', 'CD', 'EX', 'IN', 'WP$', 'MD', 'NNPS', 'JJS', 'JJR', 'SYM', 'UH', 'NNP']


table = {
    'Canada': 'NNP','Many': 'JJ', 'dollar': 'NN',  '5\\/8': 'CD', 'existing': 'VBG', 'four': 'CD',
    'facilities': 'NNS',   'manager': 'NN',   'legal': 'JJ',   'talks': 'NNS',   'settlement': 'NN',
    'issues': 'NNS', 'whose': 'WP$', 'certainly': 'RB', 'Wathen': 'NNP', 'young': 'JJ', 'to': 'TO',
    'bike': 'NN', 'UAL': 'NNP',  'health': 'NN',  'women': 'NNS',  'merchant': 'NN',  'division': 'NN',
    'woman': 'NN',  'Moon': 'NNP',  'could': 'MD',  'continues': 'VBZ',  'Mrs.': 'NNP',  'liability': 'NN',
    'me': 'PRP', 'every': 'DT', 'GM': 'NNP',  'month': 'NN',  'immediately': 'RB',
    'did': 'VBD', 'companies': 'NNS', 'standards': 'NNS', 'large': 'JJ', 'bikes': 'NNS', 'team': 'NN',
    'small': 'JJ', 'He': 'PRP', 'George': 'NNP', 'non-violent': 'JJ', 'Pinkerton': 'NNP', 'smaller': 'JJR',
    'says': 'VBZ', 'leaders': 'NNS', 'trend': 'NN', 'Lone': 'NNP', 'cash': 'NN', 'Department': 'NNP',
    'rate': 'NN', 'lawyer': 'NN', 'General': 'NNP', 'investment': 'NN', 'machines': 'NNS', 'HUD': 'NNP',
    'index': 'NN', 'Korea': 'NNP', 'adds': 'VBZ', 'business': 'NN', 'consumers': 'NNS', 'Avery': 'NNP',
    'contributed': 'VBD', '4': 'CD', 'shares': 'NNS', 'Ford': 'NNP', 'spokesman': 'NN', 'new': 'JJ',
    'firms': 'NNS', 'America': 'NNP', 'ever': 'RB', 'corn': 'NN', 'movement': 'NN', 'Revco': 'NNP',
    'Nov.': 'NNP', 'full': 'JJ', 'jury': 'NN', 'exchange': 'NN', 'never': 'RB', 'here': 'RB', 'hours': 'NNS',
    'corporation': 'NN', 'producers': 'NNS', 'protection': 'NN', 'baseball': 'NN', 'groups': 'NNS',
    'others': 'NNS', 'alone': 'RB', 'decision': 'NN', '100': 'CD', 'strong': 'JJ', 'earthquake': 'NN',
    'Warner': 'NNP', 'Sen.': 'NNP', 'employees': 'NNS', 'losses': 'NNS', 'example': 'NN', 'credit': 'NN',
    'survey': 'NN', 'analysts': 'NNS', 'Motor': 'NNP', 'social': 'JJ', 'usually': 'RB', 'gene': 'NN',
    'makes': 'VBZ', 'maker': 'NN', 'golden': 'JJ', 'via': 'IN', 'Group': 'NNP', 'family': 'NN', 'heart': 'NN',
    'outstanding': 'JJ', 'When': 'WRB', 'private': 'JJ', 'highly': 'RB', 'unit': 'NN', 'Europe': 'NNP',
    'shareholders': 'NNS', 'swings': 'NNS', 'Star': 'NNP', 'August': 'NNP', 'would': 'MD', 'remains': 'VBZ',
    'hospital': 'NN', 'June': 'NNP', 'two': 'CD', 'almost': 'RB', 'music': 'NN', 'Fe': 'NNP', '6': 'CD',
    'taken': 'VBN', 'candidates': 'NNS', 'themselves': 'PRP', 'until': 'IN', 'Those': 'DT', 'Manville': 'NNP',
    'October': 'NNP', 'LTV': 'NNP', 'Kennedy': 'NNP', 'composite': 'JJ', 'company': 'NN', 'sharply': 'RB',
    '90': 'CD', 'cases': 'NNS', 'effort': 'NN', 'must': 'MD', '1991': 'CD', '1990': 'CD', 'none': 'NN',
    'hour': 'NN', 'rights': 'NNS', 'this': 'DT', 'car': 'NN', 'clients': 'NNS', 'abortion': 'NN',
    'Pacific': 'NNP', 'nine': 'CD', 'can': 'MD', 'of': 'IN', 'industrial': 'JJ', 'making': 'VBG',
    'Rockefeller': 'NNP', 'my': 'PRP$', 'dollars': 'NNS', 'history': 'NN', 'purchases': 'NNS', 'dealers': 'NNS',
    'IBM': 'NNP', 'estate': 'NN', 'activities': 'NNS', 'tax': 'NN', 'days': 'NNS', 'states': 'NNS',
    'currency': 'NN', 'Mr.': 'NNP', 'taking': 'VBG', 'association': 'NN', 'huge': 'JJ', 'court': 'NN',
    'rather': 'RB', 'Journal': 'NNP', 'six': 'CD', 'consumer': 'NN', 'machine': 'NN', 'how': 'WRB',
    'earnings': 'NNS', 'fourth': 'JJ', 'instead': 'RB', 'Co.': 'NNP', 'MiniScribe': 'NNP', 'economy': 'NN',
    'Zealand': 'NNP', 'product': 'NN', 'ABC': 'NNP', 'information': 'NN', 'may': 'MD', 'Since': 'IN',
    'modest': 'JJ', 'district': 'NN', 'designed': 'VBN', 'law': 'NN', 'Dow': 'NNP', 'man': 'NN',
    'acquisitions': 'NNS', 'buy-out': 'NN', 'natural': 'JJ', '80': 'CD', 'Mexico': 'NNP', 'futures': 'NNS',
    'After': 'IN', 'Telerate': 'NNP', 'Oct.': 'NNP', 'banks': 'NNS', 'Fannie': 'NNP', 'operations': 'NNS',
    'Even': 'RB', 'What': 'WP', 'Philip': 'NNP', 'office': 'NN', 'Agnelli': 'NNP', 'institutional': 'JJ',
    'areas': 'NNS', 'despite': 'IN', 'soon': 'RB', 'years': 'NNS', 'course': 'NN', '4.25': 'CD', 'paper': 'NN',
    'including': 'VBG', 'committee': 'NN', 'White': 'NNP', 'still': 'RB', 'Inc': 'NNP', 'its': 'PRP$',
    'Texas': 'NNP', 'industries': 'NNS', '25': 'CD', 'His': 'PRP$', 'group': 'NN', '21': 'CD', '23': 'CD',
    'personal': 'JJ', 'facility': 'NN', '29': 'CD', 'actually': 'RB', 'coupon': 'NN', 'production': 'NN',
    'systems': 'NNS', '400': 'CD', 'Judge': 'NNP', 'weeks': 'NNS', 'main': 'JJ', 'eventually': 'RB',
    'them': 'PRP', 'greater': 'JJR', 'seeking': 'VBG', 'food': 'NN', 'auto': 'NN', 'practice': 'NN',
    'Michael': 'NNP', 'nation': 'NN', 'units': 'NNS', 'resigned': 'VBD', 'they': 'PRP', 'hands': 'NNS',
    'not': 'RB', 'R.': 'NNP', 'now': 'RB', 'Specialized': 'NNP', 'day': 'NN', 'bank': 'NN', 'Supreme': 'NNP',
    'San': 'NNP', 'always': 'RB', "O'Kicki": 'NNP', 'each': 'DT', 'Stanley': 'NNP', 'went': 'VBD',
    'quarter': 'NN', 'shareholder': 'NN', 'side': 'NN', 'bond': 'NN', 'week': 'NN', 'financial': 'JJ',
    'another': 'DT', 'doing': 'VBG', 'proposals': 'NNS', 'crimes': 'NNS', 'reduce': 'VB', 'plant': 'NN',
    'him': 'PRP', 'Treasury': 'NNP', 'lawyers': 'NNS', 'operation': 'NN', 'pills': 'NNS', 'special': 'JJ',
    'really': 'RB', 'network': 'NN', "'": 'POS', 'space': 'NN', 'house': 'NN', 'research': 'NN', 'looking': 'VBG',
    'investigation': 'NN', 'China': 'NNP', '7': 'CD', 'bankruptcy': 'NN', 'Commerce': 'NNP', 'disobedience': 'NN',
    'This': 'DT', 'cars': 'NNS', 'University': 'NNP', 'million': 'CD', 'According': 'VBG', '20': 'CD',
    'reason': 'NN', 'members': 'NNS', 'software': 'NN', 'Angeles': 'NNP', 'benefits': 'NNS', 'Congress': 'NNP',
    'September': 'NNP', 'Boston': 'NNP', 'National': 'NNP', 'computers': 'NNS', 'moment': 'NN', 'times': 'NNS',
    '7\\/8': 'CD', 'thing': 'NN', 'levels': 'NNS', 'promotion': 'NN', 'pilots': 'NNS', 'Brazil': 'NNP',
    'copper': 'NN', 'major': 'JJ', 'appeals': 'NNS', 'revenue': 'NN', 'March': 'NNP', 'There': 'EX',
    'powerful': 'JJ', 'number': 'NN', 'strategic': 'JJ', 'plants': 'NNS', 'directly': 'RB', 'fees': 'NNS',
    'corporations': 'NNS', 'Azoff': 'NNP', 'given': 'VBN', 'management': 'NN', 'Monday': 'NNP', 'lawsuits': 'NNS',
    'trillion': 'CD', 'system': 'NN', 'relations': 'NNS', 'response': 'NN', 'their': 'PRP$', '2': 'CD',
    'just': 'RB', 'stock': 'NN', 'statement': 'NN', 'which': 'WDT', 'rates': 'NNS', 'Mesa': 'NNP',
    'national': 'JJ', 'Association': 'NNP', 'too': 'RB', 'interests': 'NNS', 'ceiling': 'NN', 'growth': 'NN',
    'lot': 'NN', 'relationship': 'NN', 'acquire': 'VB', 'took': 'VBD', 'No': 'DT', 'part': 'NN', 'Mips': 'NNP',
    'surged': 'VBD', 'than': 'IN', 'steel': 'NN', '10': 'CD', 'television': 'NN', '12': 'CD', '15': 'CD',
    '14': 'CD', 'showed': 'VBD', '16': 'CD', '19': 'CD', '18': 'CD', 'largely': 'RB', 'final': 'JJ',
    'spokeswoman': 'NN', 'patients': 'NNS', 'computer': 'NN', 'Sea': 'NNP', 'were': 'VBD', 'toward': 'IN',
    'acquisition': 'NN', 'are': 'VBP', 'and': 'CC', '1.1': 'CD', 'investors': 'NNS', 'Marcos': 'NNP',
    'unchanged': 'JJ', 'partnership': 'NN', 'few': 'JJ', 'Douglas': 'NNP', 'It': 'PRP', 'already': 'RB',
    'himself': 'PRP', 'Achenbaum': 'NNP', '1': 'CD', 'clearly': 'RB', 'mountain': 'NN', 'documents': 'NNS',
    'allegedly': 'RB', 'Power': 'NNP', 'responsible': 'JJ', 'able': 'JJ', 'makers': 'NNS', 'also': 'RB',
    'internal': 'JJ', 'Germany': 'NNP', 'chairman': 'NN', 'They': 'PRP', 'funds': 'NNS', 'performance': 'NN',
    'With': 'IN', 'Bank': 'NNP', 'Jones': 'NNP', '200': 'CD', 'unless': 'IN', 'James': 'NNP',
    'transactions': 'NNS', 'who': 'WP', 'United': 'NNP', 'involving': 'VBG', 'eight': 'CD', 'letter': 'NN',
    '70': 'CD', 'services': 'NNS', 'The': 'DT', 'why': 'WRB', 'Reserve': 'NNP', 'D.': 'NNP', 'so-called': 'JJ',
    'Trust': 'NNP', 'especially': 'RB', 'NRM': 'NNP', 'Ms.': 'NNP', 'medical': 'JJ', 'Some': 'DT', 'sale': 'NN',
    'MCA': 'NNP', 'Shearson': 'NNP', '1,000': 'CD', 'ways': 'NNS', 'three-month': 'JJ', 'senior': 'JJ',
    'If': 'IN', 'typically': 'RB', 'Its': 'PRP$', 'fact': 'NN', 'laws': 'NNS', 'sector': 'NN', 'rating': 'NN',
    'particularly': 'RB', 'officer': 'NN', 'Union': 'NNP', 'minutes': 'NNS', 'Chemical': 'NNP', 'session': 'NN',
    'businesses': 'NNS', 'Under': 'IN', 'aggressive': 'JJ', 'debate': 'NN', 'staff': 'NN', 'We': 'PRP',
    'highest': 'JJS', 'based': 'VBN', 'Service': 'NNP', 'Meanwhile': 'RB', 'merger': 'NN', 'should': 'MD',
    'penalty': 'NN', 'going': 'VBG', 'black': 'JJ', 'York': 'NNP', 'equity': 'NN', '8': 'CD', 'local': 'JJ',
    'congressional': 'JJ', 'exports': 'NNS', 'his': 'PRP$', 'bonds': 'NNS', 'familiar': 'JJ', '13': 'CD',
    'expects': 'VBZ', 'While': 'IN', 'nearly': 'RB', 'closely': 'RB', 'probably': 'RB', 'during': 'IN',
    'July': 'NNP', 'volatility': 'NN', 'Because': 'IN', '17': 'CD', 'Armstrong': 'NNP', 'countries': 'NNS',
    'approach': 'NN', 'Washington': 'NNP', 'six-month': 'JJ', 'J.': 'NNP', 'she': 'PRP', 'activity': 'NN',
    'where': 'WRB', 'wrote': 'VBD', 'For': 'IN', 'Gorbachev': 'NNP', 'France': 'NNP', 'officials': 'NNS',
    'devices': 'NNS', 'discussions': 'NNS', 'jobs': 'NNS', 'news': 'NN', 'John': 'NNP', 'concern': 'NN',
    'capacity': 'NN', 'mortgage': 'NN', 'federal': 'JJ', 'currently': 'RB', 'weapons': 'NNS', 'case': 'NN',
    '3': 'CD', 'various': 'JJ', 'between': 'IN', 'Sony': 'NNP', 'yesterday': 'NN', 'Mitsubishi': 'NNP',
    'conditions': 'NNS', 'available': 'JJ', 'we': 'PRP', 'Cambria': 'NNP', 'terms': 'NNS', 'venture': 'NN',
    'parent': 'NN', 'announcement': 'NN', 'wo': 'MD', 'U.S.': 'NNP', 'attention': 'NN', 'however': 'RB',
    'agencies': 'NNS', 'offices': 'NNS', 'job': 'NN', '27': 'CD', 'opposition': 'NN', 'article': 'NN',
    'debt': 'NN', 'takeover': 'NN', 'ads': 'NNS', 'actual': 'JJ', 'Lehman': 'NNP', 'Peter': 'NNP',
    'defense': 'NN', 'avoid': 'VB', 'country': 'NN', 'trader': 'NN', 'annual': 'JJ', 'according': 'VBG',
    'drug': 'NN', 'foreign': 'JJ', '1\\/2': 'CD', 'players': 'NNS', 'became': 'VBD', 'creditors': 'NNS',
    '1\\/4': 'CD', 'long-term': 'JJ', '1\\/8': 'CD', 'comes': 'VBZ', 'among': 'IN', 'gone': 'VBN', 'ca': 'MD',
    'period': 'NN', 'community': 'NN', '60': 'CD', 'Los': 'NNP', 'tons': 'NNS', 'simply': 'RB', 'Board': 'NNP',
    'dividend': 'NN', 'labor': 'NN', 'considering': 'VBG', 'Calif.': 'NNP', 'Richard': 'NNP', 'basis': 'NN',
    'union': 'NN', 'create': 'VB', 'Chicago': 'NNP', 'political': 'JJ', 'three': 'CD', 'been': 'VBN',
    'quickly': 'RB', 'genetic': 'JJ', 'options': 'NNS', 'California': 'NNP', 'interest': 'NN',
    'indicators': 'NNS', 'proposal': 'NN', 'improve': 'VB', 'HealthVest': 'NNP', '500': 'CD', 'board': 'NN',
    'wants': 'VBZ', 'life': 'NN', 'Center': 'NNP', 'Tokyo': 'NNP', 'gas': 'NN', 'CD': 'NN', 'policy': 'NN',
    'Analysts': 'NNS', 'prices': 'NNS', 'an': 'DT', 'former': 'JJ', 'those': 'DT', 'Secretary': 'NNP',
    'And': 'CC', 'Co': 'NNP', 'publicly': 'RB', 'these': 'DT', 'consultant': 'NN', 'bill': 'NN', 'Two': 'CD',
    'budget': 'NN', 'value': 'NN', 'By': 'IN', "n't": 'RB', 'Other': 'JJ', 'PLC': 'NNP', 'owns': 'VBZ',
    'situation': 'NN', 'Tuesday': 'NNP', 'City': 'NNP', 'seven': 'CD', 'pound': 'NN', 'Northern': 'NNP',
    'On': 'IN', 'cents': 'NNS', 'health-care': 'NN', 'FHA': 'NNP', 'it': 'PRP', 'Bush': 'NNP', 'itself': 'PRP',
    'against': 'IN', 'partner': 'NN', 'You': 'PRP', 'technology': 'NN', 'pill': 'NN', 'if': 'IN', 'party': 'NN',
    'different': 'JJ', 'underwriters': 'NNS', 'things': 'NNS', 'began': 'VBD', 'administration': 'NN',
    'same': 'JJ', 'any': 'DT', 'member': 'NN', 'virtually': 'RB', 'big': 'JJ', '9': 'CD', 'products': 'NNS',
    'several': 'JJ', 'difficult': 'JJ', 'development': 'NN', 'Gen-Probe': 'NNP', 'oil': 'NN', 'temporary': 'JJ',
    'Institute': 'NNP', 'IRS': 'NNP', 'Toyota': 'NNP', 'effect': 'NN', 'hand': 'NN', 'director': 'NN',
    'action': 'NN', 'Morris': 'NNP', 'strength': 'NN', 'uses': 'VBZ', 'Sinyard': 'NNP', 'Robert': 'NNP',
    'holders': 'NNS', 'recent': 'JJ', 'transaction': 'NN', 'programs': 'NNS', 'Senate': 'NNP', 'studies': 'NNS',
    'agency': 'NN', 'without': 'IN', 'mortgages': 'NNS', 'Rep.': 'NNP', 'approval': 'NN', 'client': 'NN',
    '31': 'CD', '350': 'CD', 'direction': 'NN', 'position': 'NN', 'the': 'DT', 'corporate': 'JJ',
    'investments': 'NNS', 'researchers': 'NNS', 'latest': 'JJS', 'summer': 'NN', 'bondholders': 'NNS',
    'Chugai': 'NNP', 'quoted': 'VBN', 'from': 'IN', 'being': 'VBG', 'money': 'NN', 'competitive': 'JJ',
    'Chairman': 'NNP', 'questions': 'NNS', 'world': 'NN', 'succeeding': 'VBG', 'previous': 'JJ', 'wage': 'NN',
    'adding': 'VBG', 'buyers': 'NNS', 'death': 'NN', 'campaign': 'NN', 'equipment': 'NN', 'informal': 'JJ',
    'rose': 'VBD', 'workers': 'NNS', 'Friday': 'NNP', 'seems': 'VBZ', 'civil': 'JJ', 'nor': 'CC',
    'Although': 'IN', 'Despite': 'IN', 'Mae': 'NNP', 'Spielvogel': 'NNP', 'has': 'VBZ', 'remaining': 'VBG',
    'majority': 'NN', 'Both': 'DT', 'customers': 'NNS', 'bills': 'NNS', 'Last': 'JJ', 'Santa': 'NNP',
    'government': 'NN', 'Of': 'IN', 'possible': 'JJ', 'Among': 'IN', 'game': 'NN', 'inflation': 'NN',
    'five': 'CD', 'Chrysler': 'NNP', '30': 'CD', 'judge': 'NN', 'using': 'VBG', 'projects': 'NNS', 'loss': 'NN',
    'necessary': 'JJ', '50': 'CD', 'noted': 'VBD', 'securities': 'NNS', 'traders': 'NNS', 'yields': 'NNS',
    'payments': 'NNS', 'popular': 'JJ', 'security': 'NN', 'attorney': 'NN', 'old': 'JJ', 'often': 'RB',
    'Gulf': 'NNP', 'people': 'NNS', 'spring': 'NN', 'DES': 'NNP', 'some': 'DT', '3\\/4': 'CD',
    'Commission': 'NNP', 'economic': 'JJ', 'election': 'NN', 'Dr.': 'NNP', '5': 'CD', '3\\/8': 'CD',
    'short-term': 'JJ', 'taxpayers': 'NNS', 'trust': 'NN', 'recently': 'RB', 'Lee': 'NNP', 'for': 'IN',
    'Singapore': 'NNP', 'Moscow': 'NNP', 'However': 'RB', 'per': 'IN', 'does': 'VBZ', 'deficit': 'NN',
    'London': 'NNP', 'leader': 'NN', 'Stoll': 'NNP', 'be': 'VB', 'power': 'NN', '300': 'CD', 'Baker': 'NNP',
    'agreement': 'NN', 'David': 'NNP', 'discount': 'NN', 'Georgia-Pacific': 'NNP', 'although': 'IN',
    'brokerage': 'NN', 'loans': 'NNS', 'goods': 'NNS', 'central': 'JJ', 'anything': 'NN', 'getting': 'VBG',
    'Courtaulds': 'NNP', 'December': 'NNP', 'industry': 'NN', 'months': 'NNS', 'addition': 'NN',
    'important': 'JJ', 'airline': 'NN', 'Japan': 'NNP', 'efforts': 'NNS', 'Still': 'RB', 'slightly': 'RB',
    'or': 'CC', 'executives': 'NNS', 'Fed': 'NNP', 'managers': 'NNS', 'significant': 'JJ', 'Stoltzman': 'NNP',
    'previously': 'RB', 'into': 'IN', 'within': 'IN', 'NEC': 'NNP', '62': 'CD', 'nothing': 'NN', 'But': 'CC',
    'arbitrage': 'NN', 'strategy': 'NN', 'your': 'PRP$', 'utility': 'NN', '1986': 'CD', '1987': 'CD',
    'additional': 'JJ', 'area': 'NN', 'housing': 'NN', 'legislation': 'NN', '1988': 'CD', '1989': 'CD',
    'way': 'NN', 'suit': 'NN', 'biggest': 'JJS', 'Corp': 'NNP', 'November': 'NNP', 'was': 'VBD', 'war': 'NN',
    'Steel': 'NNP', 'billion': 'CD', 'Kidder': 'NNP', 'something': 'NN', 'January': 'NNP', 'institutions': 'NNS',
    'idea': 'NN', 'volume': 'NN', 'contract': 'NN', 'construction': 'NN', 'brain': 'NN', 'Ltd.': 'NNP',
    'Healthcare': 'NNP', 'subsidiary': 'NN', 'line': 'NN', 'trying': 'VBG', 'active': 'JJ', 'analyst': 'NN',
    'raising': 'VBG', 'he': 'PRP', 'Industrial': 'NNP', 'largest': 'JJS', 'Wall': 'NNP', 'bids': 'NNS',
    'us': 'PRP', 'County': 'NNP', 'maturity': 'NN', 'Britain': 'NNP', "'re": 'VBP', 'today': 'NN', 'SEC': 'NNP',
    'problem': 'NN', 'piece': 'NN', 'similar': 'JJ', 'RU-486': 'NNP', '150': 'CD', 'changes': 'NNS', 'ad': 'NN',
    'certain': 'JJ', 'year': 'NN', 'am': 'VBP', 'Cross': 'NNP', 'evidence': 'NN', 'To': 'TO', 'at': 'IN',
    'our': 'PRP$', 'proceeds': 'NNS', 'again': 'RB', 'Francisco': 'NNP', "'ll": 'MD', 'floor': 'NN',
    'May': 'NNP', 'Jr.': 'NNP', 'stake': 'NN', 'when': 'WRB', 'Yesterday': 'NN', '40': 'CD', 'insurance': 'NN',
    'These': 'DT', 'other': 'JJ', 'role': 'NN', 'income': 'NN', 'department': 'NN', 'you': 'PRP',
    'William': 'NNP', 'At': 'IN', 'junk': 'NN', 'Hunt': 'NNP', 'problems': 'NNS', 'utilities': 'NNS',
    'includes': 'VBZ', 'April': 'NNP', 'fell': 'VBD', 'Morgan': 'NNP', 'biotechnology': 'NN', "'m": 'VBP',
    'stocks': 'NNS', 'sides': 'NNS', 'ago': 'RB', 'reorganization': 'NN', 'assets': 'NNS', 'Estate': 'NNP',
    'vice': 'NN', 'came': 'VBD', 'percentage': 'NN', 'An': 'DT', 'directors': 'NNS', 'Street': 'NNP',
    'pension': 'NN', 'time': 'NN', 'international': 'JJ', 'having': 'VBG', 'profits': 'NNS', 'brokers': 'NNS'}